/* Auto-generated encrypted TensorFlow Lite model */
/* Generated by model_encryptor.py */

#ifndef ENCRYPTED_MODEL_H
#define ENCRYPTED_MODEL_H

#include <stdint.h>
#include <stddef.h>

/* Encrypted model data */
extern const uint8_t encrypted_audio_preprocessor_int8_data[];
extern const size_t encrypted_audio_preprocessor_int8_size;

/* Encryption key (should be stored securely) */
extern const uint8_t encrypted_audio_preprocessor_int8_key[];
extern const size_t encrypted_audio_preprocessor_int8_key_size;

/* Model metadata */
#define ENCRYPTED_AUDIO_PREPROCESSOR_INT8_MAGIC_HEADER 0x4D4C4654
#define ENCRYPTED_AUDIO_PREPROCESSOR_INT8_VERSION 1

#endif /* ENCRYPTED_MODEL_H */
