/* Auto-generated encrypted TinyMAIX model */
/* Generated by tinymaix_model_encryptor.py */

#ifndef ENCRYPTED_TINYMAIX_MODEL_H
#define ENCRYPTED_TINYMAIX_MODEL_H

#include <stdint.h>
#include <stddef.h>

/* Encrypted model data */
extern const uint8_t encrypted_mdl_data_data[];
extern const size_t encrypted_mdl_data_size;

/* Model metadata */
#define ENCRYPTED_MDL_DATA_MAGIC_HEADER 0x58414D54
#define ENCRYPTED_MDL_DATA_VERSION 3

#endif /* ENCRYPTED_TINYMAIX_MODEL_H */
